### ISSUE TITLE
Relock throws an error but succeeds

### ISSUE THREAD

**Issue by jamescowling** [celo-org/celo-monorepo#2455]
If you try to re-lock gold that is pending unlocking then it succeeds but shows an error:

```
james@accounts:~/census-ops$ celocli lockedgold:lock --from $CELO_VALIDATOR_ADDRESS --value 3000686416668556302541
Running Checks:
   ✔  Value [3000686416668556302541] is > 0
   ✔  687d149244d58fefdcc321b592b994472ba0080f is a registered Account
Running Checks:
   ✔  Account has at least 0 cGold
SendTransaction: relock
txHash: 0x788a73b4973e4177166d56122a34c9c4d46945b3e901a6a694887446841cfae2
Sending Transaction: relock... done
Sending Transaction: lock... !
Error: Returned error: gas required exceeds allowance or always failing transaction
    at Object.ErrorResponse (~/.nvm/versions/node/v10.18.0/lib/node_modules/@celo/celocli/node_modules/web3-core-helpers/src/errors.js:29:16)
    at ~/.nvm/versions/node/v10.18.0/lib/node_modules/@celo/celocli/node_modules/web3-core-requestmanager/src/index.js:140:36
    at callbackDecorator (~/.nvm/versions/node/v10.18.0/lib/node_modules/@celo/celocli/src/utils/eth-debug-provider.ts:16:7)
    at XMLHttpRequest.request.onreadystatechange (~/.nvm/versions/node/v10.18.0/lib/node_modules/@celo/celocli/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (~/.nvm/versions/node/v10.18.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (~/.nvm/versions/node/v10.18.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (~/.nvm/versions/node/v10.18.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (~/.nvm/versions/node/v10.18.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
```

state before this command:
```
james@accounts:~/census-ops$ celocli lockedgold:show $CELO_VALIDATOR_ADDRESS
Running Checks:
   ✔  687d149244d58fefdcc321b592b994472ba0080f is a registered Account
lockedGold:
  total: 2170069882894147954 (~2.17 10^18)
  nonvoting: 0
  requirement: 0
pendingWithdrawals:
  0:
    time: 1579146743
    value: 3000686416668556302541 (~3000.69 10^18)
```

state after this command:
```
james@accounts:~/census-ops$ celocli lockedgold:show $CELO_VALIDATOR_ADDRESS
Running Checks:
   ✔  687d149244d58fefdcc321b592b994472ba0080f is a registered Account
lockedGold:
  total: 3002856486551450450495 (~3002.86 10^18)
  nonvoting: 3000686416668556302541 (~3000.69 10^18)
  requirement: 0
pendingWithdrawals:
```
