### ISSUE TITLE
Pending withdrawal amount appears to change

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#2528]
Submitted request to unlock 10k cGLD:

```
ubuntu@local:~$ celocli lockedgold:unlock --from $CELO_VALIDATOR_GROUP_ADDRESS --value 10000000280895051885125
Running Checks:
   ✔  bcd25468e4d433ac442b87f32b37b39678bf7077 is a registered Account 
   ✔  Account has at least 10000.000280895051885125 non-voting Locked Gold 
SendTransaction: unlock
txHash: 0xa926a7438db718a618d987ca90ebac055d2d26335bd00e17c620d25a76d1c5e6
Sending Transaction: unlock... done
```
Confirmed the transaction worked: 
```
ubuntu@local:~$ celocli lockedgold:show $CELO_VALIDATOR_GROUP_ADDRESS 
Running Checks:
   :heavy_check_mark:  bcd25468e4d433ac442b87f32b37b39678bf7077 is a registered Account 
lockedGold: 
  total: 34259077155273894846932 (~34259.08 10^18)
  nonvoting: 0 
  requirement: 20000000000000000000000 (~20000 10^18)
pendingWithdrawals: 
  0: 
    time: 1579850606 
    value: 10000000280895051885125 (~10000 10^18)
```

An hour later I see that 1137 is non-voting and only 8862 is pending withdrawal. 
 ```
ubuntu@local:~$ celocli lockedgold:show $CELO_VALIDATOR_GROUP_ADDRESS
Running Checks:
   ✔  bcd25468e4d433ac442b87f32b37b39678bf7077 is a registered Account 
lockedGold: 
  total: 35401364274507975410829 (~35401.36 10^18)
  nonvoting: 1137742738696896444231 (~1137.74 10^18)
  requirement: 20000000000000000000000 (~20000 10^18)
pendingWithdrawals: 
  0: 
    time: 1579850606 
    value: 8862257542198155440894 (~8862.26 10^18)
```
