### ISSUE TITLE
Release 3 on Baklava

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6676]
Deploy and Test

**Comment by nambrot** [comment]
Note that deploys need to include https://github.com/celo-org/celo-monorepo/pull/6937

**Comment by yorhodes** [comment]
`yarn make-release -b celo-core-contracts-v3.rc0 -n baklava -r release3_report.json -i ./releaseData/initializationData/release3.json -p proposal.json -f "0x0cc59ed03b3e763c02d54d695ffe353055f1502d"`
outputs
```json
[
  {
    "contract": "BlockchainParametersProxy",
    "function": "_setImplementation",
    "args": [
      "0x9B80a40BBa80509CFDdB49F601bbA1345D2Ed80c"
    ],
    "value": "0"
  },
  {
    "contract": "Registry",
    "function": "setAddressFor",
    "args": [
      "ExchangeEUR",
      "0xc2CDC03C417D18d0Fd757bc9b59b12A763C71Eb2"
    ],
    "value": "0",
    "description": "Registry: ExchangeEUR -> 0xc2CDC03C417D18d0Fd757bc9b59b12A763C71Eb2"
  },
  {
    "contract": "ExchangeEURProxy",
    "function": "_setAndInitializeImplementation",
    "args": [
      "0x641b4d437d59386558d7C226F1DA38Df4FE04ef9",
      "0x86489ba9000000000000000000000000000000000000000000000000000000000000ce10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010f0cf064dd59200000000000000000000000000000000000000000000000000046791fc84e07d00000000000000000000000000000000000000000000000000000000000000000012c0000000000000000000000000000000000000000000000000000000000000005"
    ],
    "value": "0"
  },
  {
    "contract": "GovernanceProxy",
    "function": "_setImplementation",
    "args": [
      "0xc869C6D01c47D9bd919F2607E3E28877cbCa7547"
    ],
    "value": "0"
  },
  {
    "contract": "ReserveProxy",
    "function": "_setImplementation",
    "args": [
      "0x361f20667DEE2f029acc852E990Cc0664EDfB433"
    ],
    "value": "0"
  },
  {
    "contract": "StableTokenProxy",
    "function": "_setImplementation",
    "args": [
      "0x535Ca699B0887408290716d23959c614E180E774"
    ],
    "value": "0"
  },
  {
    "contract": "Registry",
    "function": "setAddressFor",
    "args": [
      "StableTokenEUR",
      "0xA5fd742a9354a566513dD697834DB3af59D64cF0"
    ],
    "value": "0",
    "description": "Registry: StableTokenEUR -> 0xA5fd742a9354a566513dD697834DB3af59D64cF0"
  },
  {
    "contract": "StableTokenEURProxy",
    "function": "_setAndInitializeImplementation",
    "args": [
      "0x704dFa468f8bD3cdb0Fe8Da37bbC8c64ce272F1A",
      "0x1e4f0e03000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001600000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000ce1000000000000000000000000000000000000000000000d3c21bcecceda10000000000000000000000000000000000000000000000000000000000000002d1cd4000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000260000000000000000000000000000000000000000000000000000000000000000943656c6f204575726f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000463455552000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000d533ca259b330c7a88f74e000a3faea2d63b7972000000000000000000000000989e1a3b344a43911e02ccc609d469fbc15ab1f1000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000001a784379d99db4200000000000000000000000000000000000000000000000004f68ca6d8cd91c6000000000000000000000000000000000000000000000000000000000000000000000b45786368616e6765455552000000000000000000000000000000000000000000"
    ],
    "value": "0"
  },
  {
    "contract": "ValidatorsProxy",
    "function": "_setImplementation",
    "args": [
      "0x2E1Ce4fe805bD630CddfA2bFD29637E0059550cD"
    ],
    "value": "0"
  }
]
```

**Comment by yorhodes** [comment]
`yarn ts-node scripts/make-release-3-changes.ts --input_proposal proposal.json --output_proposal modified_proposal.json`
outputs
```json
[
  {
    "contract": "BlockchainParametersProxy",
    "function": "_setImplementation",
    "args": [
      "0x9B80a40BBa80509CFDdB49F601bbA1345D2Ed80c"
    ],
    "value": "0"
  },
  {
    "contract": "Registry",
    "function": "setAddressFor",
    "args": [
      "ExchangeEUR",
      "0xc2CDC03C417D18d0Fd757bc9b59b12A763C71Eb2"
    ],
    "value": "0",
    "description": "Registry: ExchangeEUR -> 0xc2CDC03C417D18d0Fd757bc9b59b12A763C71Eb2"
  },
  {
    "contract": "ExchangeEURProxy",
    "function": "_setAndInitializeImplementation",
    "args": [
      "0x641b4d437d59386558d7C226F1DA38Df4FE04ef9",
      "0x86489ba9000000000000000000000000000000000000000000000000000000000000ce10000000000000000000000000A5fd742a9354a566513dD697834DB3af59D64cF000000000000000000000000000000000000000000000010f0cf064dd59200000000000000000000000000000000000000000000000000046791fc84e07d00000000000000000000000000000000000000000000000000000000000000000012c0000000000000000000000000000000000000000000000000000000000000005"
    ],
    "value": "0"
  },
  {
    "contract": "GovernanceProxy",
    "function": "_setImplementation",
    "args": [
      "0xc869C6D01c47D9bd919F2607E3E28877cbCa7547"
    ],
    "value": "0"
  },
  {
    "contract": "ReserveProxy",
    "function": "_setImplementation",
    "args": [
      "0x361f20667DEE2f029acc852E990Cc0664EDfB433"
    ],
    "value": "0"
  },
  {
    "contract": "StableTokenProxy",
    "function": "_setImplementation",
    "args": [
      "0x535Ca699B0887408290716d23959c614E180E774"
    ],
    "value": "0"
  },
  {
    "contract": "Registry",
    "function": "setAddressFor",
    "args": [
      "StableTokenEUR",
      "0xA5fd742a9354a566513dD697834DB3af59D64cF0"
    ],
    "value": "0",
    "description": "Registry: StableTokenEUR -> 0xA5fd742a9354a566513dD697834DB3af59D64cF0"
  },
  {
    "contract": "StableTokenEURProxy",
    "function": "_setAndInitializeImplementation",
    "args": [
      "0x704dFa468f8bD3cdb0Fe8Da37bbC8c64ce272F1A",
      "0x1e4f0e03000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001600000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000ce1000000000000000000000000000000000000000000000d3c21bcecceda10000000000000000000000000000000000000000000000000000000000000002d1cd4000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000260000000000000000000000000000000000000000000000000000000000000000943656c6f204575726f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000463455552000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000d533ca259b330c7a88f74e000a3faea2d63b7972000000000000000000000000989e1a3b344a43911e02ccc609d469fbc15ab1f1000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000001a784379d99db4200000000000000000000000000000000000000000000000004f68ca6d8cd91c6000000000000000000000000000000000000000000000000000000000000000000000b45786368616e6765455552000000000000000000000000000000000000000000"
    ],
    "value": "0"
  },
  {
    "contract": "ValidatorsProxy",
    "function": "_setImplementation",
    "args": [
      "0x2E1Ce4fe805bD630CddfA2bFD29637E0059550cD"
    ],
    "value": "0"
  }
]
```

**Comment by martinvol** [comment]
seems like the address `0x989e1a3B344A43911e02cCC609D469fbc15AB1F1` for the cEUR pre-mint needs to be changed for one we could use for testing

**Comment by yorhodes** [comment]
proposed 
```yaml
proposal:
  0:
    contract: BlockchainParametersProxy
    function: _setImplementation
    args:
      0: 0x0832A8B20AF9cF7B339387Ec37e25B054CC7a99E
    params:
      implementation: 0x0832A8B20AF9cF7B339387Ec37e25B054CC7a99E
    value: 0
  1:
    contract: Registry
    function: setAddressFor
    args:
      0: ExchangeEUR
      1: 0xC200CD8ac71A63e38646C34b51ee3cBA159dB544
    params:
      identifier: ExchangeEUR
      addr: 0xC200CD8ac71A63e38646C34b51ee3cBA159dB544
    value: 0
  2:
    contract: ExchangeEURProxy
    function: _setAndInitializeImplementation
    args:
      0: 0x25e07DE338C4CA864675df040bbfd8eCb6f29556
      1: 0x86489ba9000000000000000000000000000000000000000000000000000000000000ce10000000000000000000000000f9ece301247ad2ce21894941830a2470f4e774ca00000000000000000000000000000000000000000000010f0cf064dd59200000000000000000000000000000000000000000000000000046791fc84e07d00000000000000000000000000000000000000000000000000000000000000000012c0000000000000000000000000000000000000000000000000000000000000005
    params:
      implementation: 0x25e07DE338C4CA864675df040bbfd8eCb6f29556
      callbackData: 0x86489ba9000000000000000000000000000000000000000000000000000000000000ce10000000000000000000000000f9ece301247ad2ce21894941830a2470f4e774ca00000000000000000000000000000000000000000000010f0cf064dd59200000000000000000000000000000000000000000000000000046791fc84e07d00000000000000000000000000000000000000000000000000000000000000000012c0000000000000000000000000000000000000000000000000000000000000005
      initialize@86489ba9:
        registryAddress: 0x000000000000000000000000000000000000ce10
        stableToken: 0xf9ecE301247aD2CE21894941830A2470f4E774ca
        _spread: 5000000000000000000000
        _reserveFraction: 1300000000000000000000
        _updateFrequency: 300
        _minimumReports: 5
    value: 0
  3:
    contract: GovernanceProxy
    function: _setImplementation
    args:
      0: 0xC95233d1BCEaF23Af8427d9E8208d3AA684a4A3a
    params:
      implementation: 0xC95233d1BCEaF23Af8427d9E8208d3AA684a4A3a
    value: 0
  4:
    contract: ReserveProxy
    function: _setImplementation
    args:
      0: 0xD1603cEe8b43F7D2e94F933C74e480A9CEad34f2
    params:
      implementation: 0xD1603cEe8b43F7D2e94F933C74e480A9CEad34f2
    value: 0
  5:
    contract: StableTokenProxy
    function: _setImplementation
    args:
      0: 0xeD949d605af3C59Eab686a0Da48268f9d4165070
    params:
      implementation: 0xeD949d605af3C59Eab686a0Da48268f9d4165070
    value: 0
  6:
    contract: Registry
    function: setAddressFor
    args:
      0: StableTokenEUR
      1: 0xf9ecE301247aD2CE21894941830A2470f4E774ca
    params:
      identifier: StableTokenEUR
      addr: 0xf9ecE301247aD2CE21894941830A2470f4E774ca
    value: 0
  7:
    contract: StableTokenEURProxy
    function: _setAndInitializeImplementation
    args:
      0: 0x58a8E474801374F838008141ca08755F6F938467
      1: 0x1e4f0e03000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001600000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000ce1000000000000000000000000000000000000000000000d3c21bcecceda10000000000000000000000000000000000000000000000000000000000000002d1cd4000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000260000000000000000000000000000000000000000000000000000000000000000943656c6f204575726f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000046345555200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000028443b1d87db521320a6517a4f1b6ead77f8c811000000000000000000000000989e1a3b344a43911e02ccc609d469fbc15ab1f1000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000001a784379d99db4200000000000000000000000000000000000000000000000004f68ca6d8cd91c6000000000000000000000000000000000000000000000000000000000000000000000b45786368616e6765455552000000000000000000000000000000000000000000
    params:
      implementation: 0x58a8E474801374F838008141ca08755F6F938467
      callbackData: 0x1e4f0e03000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001600000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000ce1000000000000000000000000000000000000000000000d3c21bcecceda10000000000000000000000000000000000000000000000000000000000000002d1cd4000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000260000000000000000000000000000000000000000000000000000000000000000943656c6f204575726f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000046345555200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000028443b1d87db521320a6517a4f1b6ead77f8c811000000000000000000000000989e1a3b344a43911e02ccc609d469fbc15ab1f1000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000001a784379d99db4200000000000000000000000000000000000000000000000004f68ca6d8cd91c6000000000000000000000000000000000000000000000000000000000000000000000b45786368616e6765455552000000000000000000000000000000000000000000
      initialize@1e4f0e03:
        _name: Celo Euro
        _symbol: cEUR
        _decimals: 18
        registryAddress: 0x000000000000000000000000000000000000ce10
        inflationRate: 1000000000000000000000000
        inflationFactorUpdatePeriod: 47304000
        initialBalanceAddresses:
          0: 0x28443b1d87db521320a6517A4F1B6Ead77F8C811
          1: 0x989e1a3B344A43911e02cCC609D469fbc15AB1F1
        initialBalanceValues:
          0: 2000000000000000000000000
          1: 6000000000000000000000000
        exchangeIdentifier: ExchangeEUR
    value: 0
  8:
    contract: ValidatorsProxy
    function: _setImplementation
    args:
      0: 0xf488aA0d482BB0B07E56Cd0324eFe29a6ae3B35C
    params:
      implementation: 0xf488aA0d482BB0B07E56Cd0324eFe29a6ae3B35C
    value: 0
metadata:
  proposer: 0x0Cc59Ed03B3e763c02d54D695FFE353055f1502D
  deposit: 100000000000000000000 (~1.000e+20)
  timestamp: 1614717145 (~1.615e+9)
  transactionCount: 9
  descriptionURL: https://github.com/celo-org/celo-proposals/blob/yorke.yaz.core_contracts_3/CGPs/0022.md
stage: Queued
passed: false
approved: false
upvotes: 2620000000000000000000000 (~2.620e+24)
schedule:
  Queued: Tue, Mar 2, 2021 12:32 PM UTC-08:00
  Expiration: Tue, Mar 30, 2021 1:32 PM UTC-07:00
  ```
  don't have access to the approver address
